### ISSUE TITLE
Actividad 9 Diagrama de Clases y de Secuencia

### ISSUE THREAD

**Issue by Daniel-Velasco-Lopez** [SistemasTecTlaxiaco/actividad-8-diagrama-de-clases-secuencia-equipo-jad#1]
Reporte actualizado, añadiendo los diagramas de secuencia faltantes

[Diagrama de Clases y Secuencia.pdf](https://github.com/user-attachments/files/18044367/Diagrama.de.Clases.y.Secuencia.pdf)

**Comment by Daisy-GonzalezLita12** [comment]
De acuerdo a la rúbrica obtuviste 28%.

**Comment by josealfredo79** [comment]
**Por cada CASO DE USO un DIAGRAMA DE SECUENCIA**

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
